/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Game = IDL.Record({
  'id' : IDL.Text,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'embedUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getFeaturedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getGameById' : IDL.Func([IDL.Text], [Game], ['query']),
  'searchGames' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Game = IDL.Record({
    'id' : IDL.Text,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'embedUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getFeaturedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getGameById' : IDL.Func([IDL.Text], [Game], ['query']),
    'searchGames' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };